# Generated by Django 5.1.4 on 2026-06-23 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('content_calendar', '0001_initial'),
        ('generation', '0001_initial'),
        ('special_days', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcalendarentry',
            name='active_generation_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='generation.generationversion'),
        ),
        migrations.AddField(
            model_name='contentcalendarentry',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='brands.brandprofile'),
        ),
        migrations.AddField(
            model_name='contentcalendarentry',
            name='brand_holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_entries', to='special_days.brandholiday'),
        ),
        migrations.AddField(
            model_name='contentcalendarentry',
            name='parent_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='content_calendar.contentcalendarentry'),
        ),
        migrations.AddField(
            model_name='contentcalendarentry',
            name='suggestion_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='content_calendar.calendarsuggestionbatch'),
        ),
        migrations.AddIndex(
            model_name='contentcalendarentry',
            index=models.Index(fields=['brand', 'scheduled_date'], name='content_cal_brand_i_0118ff_idx'),
        ),
        migrations.AddIndex(
            model_name='contentcalendarentry',
            index=models.Index(fields=['brand', 'status'], name='content_cal_brand_i_076637_idx'),
        ),
    ]
