# Generated by Django 5.1.4 on 2026-06-23 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('content_calendar', '0001_initial'),
        ('generation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh_key', models.CharField(max_length=255)),
                ('auth_key', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderEscalationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_24h', models.BooleanField(default=False)),
                ('sent_12h', models.BooleanField(default=False)),
                ('sent_3h', models.BooleanField(default=False)),
                ('sent_due', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_state', to='content_calendar.contentcalendarentry')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('generation_done', 'Generation done'), ('generation_failed', 'Generation failed'), ('reminder_24h', 'Reminder 24h'), ('reminder_12h', 'Reminder 12h'), ('reminder_3h', 'Reminder 3h'), ('reminder_due', 'Reminder due'), ('suggestion_batch_ready', 'Suggestion batch ready')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('channel', models.CharField(choices=[('web_push', 'Web push'), ('in_app_only', 'In-app only')], default='web_push', max_length=20)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped_no_subscription', 'Skipped (no subscription)')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='brands.brandprofile')),
                ('related_calendar_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='content_calendar.contentcalendarentry')),
                ('related_generation_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='generation.generationversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['related_calendar_entry'], name='notificatio_related_bf715b_idx')],
            },
        ),
    ]
