# Generated by Django 5.1.4 on 2026-06-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushsubscription',
            name='auth_key',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='p256dh_key',
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='registration_token',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('fcm', 'Firebase Cloud Messaging'), ('in_app_only', 'In-app only')], default='fcm', max_length=20),
        ),
    ]
