# Generated by Django 5.1.4 on 2026-06-23 21:46

import django.db.models.deletion
import generation.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_calendar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveSmallIntegerField()),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('status', models.CharField(choices=[('pending_prompt', 'Pending prompt'), ('prompt_ready', 'Prompt ready'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending_prompt', max_length=20)),
                ('claude_prompt_text', models.TextField(blank=True)),
                ('grok_request_payload', models.JSONField(blank=True, default=dict)),
                ('grok_request_id', models.CharField(blank=True, max_length=255)),
                ('grok_response_meta', models.JSONField(blank=True, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to=generation.models.generation_media_upload_path)),
                ('thumbnail_file', models.FileField(blank=True, null=True, upload_to=generation.models.generation_media_upload_path)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_versions', to='content_calendar.contentcalendarentry')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['calendar_entry', 'version_number'], name='generation__calenda_b4acb9_idx'), models.Index(fields=['status'], name='generation__status_9fe9f7_idx')],
                'constraints': [models.UniqueConstraint(fields=('calendar_entry', 'version_number'), name='unique_version_per_entry')],
            },
        ),
    ]
