# Generated by Django 5.1.4 on 2026-06-23 21:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('content_calendar', '0001_initial'),
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('claude', 'Claude'), ('grok', 'Grok')], max_length=10)),
                ('model', models.CharField(max_length=100)),
                ('operation', models.CharField(choices=[('vision_analysis', 'Vision analysis'), ('prompt_generation', 'Prompt generation'), ('suggestion_generation', 'Suggestion generation'), ('image_generation', 'Image generation'), ('video_generation', 'Video generation')], max_length=30)),
                ('cost_in_usd_ticks', models.BigIntegerField(blank=True, null=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='brands.brandprofile')),
                ('brand_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='brands.brandasset')),
                ('generation_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='generation.generationversion')),
                ('suggestion_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='content_calendar.calendarsuggestionbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['brand', 'created_at'], name='usage_usage_brand_i_31b06e_idx'), models.Index(fields=['brand', 'provider'], name='usage_usage_brand_i_0d4547_idx')],
            },
        ),
    ]
