# Generated by Django 5.1.4 on 2026-06-23 21:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryHolidayTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=2, unique=True)),
                ('popular_days_last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('popular_days_source_meta', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryHolidayTemplateEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('official', 'Official'), ('religious', 'Religious'), ('popular', 'Popular')], max_length=20)),
                ('source', models.CharField(choices=[('holidays_lib', 'holidays library'), ('claude_curated', 'Claude curated')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='special_days.countryholidaytemplate')),
            ],
        ),
        migrations.CreateModel(
            name='BrandHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('official', 'Official'), ('religious', 'Religious'), ('popular', 'Popular')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='brands.brandprofile')),
                ('source_template_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_holidays', to='special_days.countryholidaytemplateentry')),
            ],
        ),
        migrations.AddIndex(
            model_name='countryholidaytemplateentry',
            index=models.Index(fields=['template', 'date'], name='special_day_templat_52e1f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='countryholidaytemplateentry',
            constraint=models.UniqueConstraint(fields=('template', 'name', 'date'), name='unique_template_entry'),
        ),
        migrations.AddIndex(
            model_name='brandholiday',
            index=models.Index(fields=['brand', 'date'], name='special_day_brand_i_0b5bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='brandholiday',
            index=models.Index(fields=['brand', 'is_active'], name='special_day_brand_i_f5caec_idx'),
        ),
    ]
