# Generated by Django 5.1.4 on 2026-06-23 21:46

import brands.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('style_description', models.TextField(blank=True)),
                ('voice_tone_description', models.TextField(blank=True)),
                ('voice_traits', models.JSONField(blank=True, default=list)),
                ('target_audience', models.TextField(blank=True)),
                ('font_primary', models.CharField(blank=True, max_length=255)),
                ('font_secondary', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('default_publish_time', models.TimeField(default='09:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='agencies.agency')),
            ],
        ),
        migrations.CreateModel(
            name='BrandColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('hex_value', models.CharField(max_length=7)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('extracted_from_logo', 'Extracted from logo')], default='manual', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='brands.brandprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('logo', 'Logo'), ('identity_document', 'Identity document')], max_length=30)),
                ('file', models.FileField(upload_to=brands.models.brand_asset_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('page_images', models.JSONField(blank=True, default=list)),
                ('claude_vision_analysis', models.JSONField(blank=True, null=True)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_primary', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='brands.brandprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BrandAIContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_keywords', models.JSONField(blank=True, default=list)),
                ('mood_descriptors', models.JSONField(blank=True, default=list)),
                ('visual_donts', models.JSONField(blank=True, default=list)),
                ('enrichment_summary', models.TextField(blank=True)),
                ('last_enriched_at', models.DateTimeField(blank=True, null=True)),
                ('source_assets', models.ManyToManyField(blank=True, related_name='ai_context_runs', to='brands.brandasset')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_context', to='brands.brandprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='brandprofile',
            index=models.Index(fields=['agency', 'is_active'], name='brands_bran_agency__2e7e0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='brandprofile',
            constraint=models.UniqueConstraint(fields=('agency', 'slug'), name='unique_brand_slug_per_agency'),
        ),
        migrations.AddIndex(
            model_name='brandasset',
            index=models.Index(fields=['brand', 'asset_type'], name='brands_bran_brand_i_c3413a_idx'),
        ),
    ]
